name: publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            pip install \
              --only-binary=:all: \
              --platform any \
              --python-version 39 \
              --implementation py \
              --abi none \
              --target site-packages \
              ezdxf==1.0.3
          elif [ "$RUNNER_OS" == "Windows" ] || [ "$RUNNER_OS" == "macOS" ]; then
            python3 -m pip install -t site-packages ezdxf==1.0.3
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi

      - name: Generate release tag
        id: tag
        shell: bash
        run: echo "release_tag=build_$(date +"%Y.%m.%d_%H-%M")" >> "$GITHUB_OUTPUT"

      - name: dist
        shell: bash
        run: |
          mkdir -p dist/sketch-export-dxf
          mv LICENSE README.md sketch-export-dxf.manifest sketch-export-dxf.py dist/sketch-export-dxf
          mv src dist/sketch-export-dxf
          mv site-packages dist/sketch-export-dxf
          rm -rf dist/**/__pycache__

      - name: Package for Linux
        if: runner.os == 'Linux'
        run: |
          cd dist
          zip universal-${{ steps.tag.outputs.release_tag }}.zip -r sketch-export-dxf

      - name: Package for macOS
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip mac-${{ steps.tag.outputs.release_tag }}.zip -r sketch-export-dxf

      - name: Package for Windows
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          cd dist
          Compress-Archive -Path sketch-export-dxf -Destination windows-${{ steps.tag.outputs.release_tag }}.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: dist/*.zip
