name: publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ["3.9"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: python3 -m pip install -t site-packages ezdxf==1.0.3
      - name: Generate release tag
        id: tag
        shell: bash
        run: echo "release_tag=build_$(date +"%Y.%m.%d_%H-%M")" >> "$GITHUB_OUTPUT"

      - name: Zip
        shell: bash
        run: |
          mkdir dist
          mv LICENSE README.md sketch-export-dxf.manifest sketch-export-dxf.py dist
          mv src dist
          mv site-packages/ dist
          zip ${{ matrix.os }}-${{ steps.tag.outputs.release_tag }}.zip -r dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: ${{ matrix.os }}-${{ steps.tag.outputs.release_tag }}.zip
